Question 1: Create a 4X2 integer array and Prints its attributes
Note: element must be a type of unsigned int16. And print the following Attributes: –

The shape of an array.
Array dimensions.
The Length of each element of the array in bytes.

In [1]:
import numpy as np

In [3]:
arr= np.arange(0,8,dtype=np.uint16).reshape(4,2)

In [4]:
arr.shape

(4, 2)

In [12]:
np.size(arr,1)

2

In [13]:
arr.itemsize

2

Question 2: Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10

In [15]:
arr2 = np.arange(100,201,10)

In [16]:
arr2

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200])

Question 3: Following is the provided numPy array. return array of items in the third column from all rows
import numpy
sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
Expected Output:

Printing Input Array
[[11 22 33]
 [44 55 66]
 [77 88 99]]

 Printing array of items in the third column from all rows
[22 55 88]

In [17]:
arr3 = np.array([[11,22,33],[44,55,66],[77,88,99]])

In [18]:
arr3

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [23]:
arr4=np.array(arr3[:,1:2])

In [24]:
arr4

array([[22],
       [55],
       [88]])

Question 4: Following is the given numpy array return array of odd rows and even columns
import numpy

sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
Expected Output:

Printing Input Array
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]

 Printing array of odd rows and even columns
[[ 6 12]
 [30 36]
 [54 60]]

In [26]:
arr5 = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])

In [27]:
arr5[0:6:2,1::2]

array([[ 6, 12],
       [30, 36],
       [54, 60]])

Question 5: Add the following two NumPy arrays and Modify a result array by calculating the square root of each element
import numpy

arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])
Expected Output:

addition of two arrays is 

[[20 39 33]
 [25 25 28]]

Result array after calculating the square root of all elements

[[ 400 1521 1089]
 [ 625  625  784]]

In [28]:
ar1=np.array([[5, 6, 9], [21 ,18, 27]])

In [29]:
ar2=np.array([[15 ,33, 24], [4 ,7, 1]])

In [31]:
s= ar1 + ar2

In [32]:
s

array([[20, 39, 33],
       [25, 25, 28]])

In [33]:
np.sqrt(s)

array([[4.47213595, 6.244998  , 5.74456265],
       [5.        , 5.        , 5.29150262]])

Question 7; Sort following NumPy array
7.1- by the second row and
7.2-by the second column
import numpy
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
Expected Output:

Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]

Sorting Original array by secoond row
[[73 43 34]
 [12 22 82]
 [66 94 53]]

Sorting Original array by secoond column
[[82 22 12]
 [34 43 73]
 [53 94 66]]

In [34]:
samp=np.array([[34,43,73],[82,22,12],[53,94,66]])

In [40]:
for i in range(1,3):
    for j in range(0,3-i):
        if(samp[1][j]>samp[1][j+1]):
            for k in range(3):
                temp=samp[k][j]
                samp[k][j]=samp[k][j+1]
                samp[k][j+1]=temp
samp

array([[73, 43, 34],
       [12, 22, 82],
       [66, 94, 53]])

In [43]:
samp=np.array([[34,43,73],[82,22,12],[53,94,66]])
for i in range(1,3):
    for j in range(0,3-i):
        if(samp[j][1]>samp[j+1][1]):
            for k in range(3):
                temp=samp[j][k]
                samp[j][k]=samp[j+1][k]
                samp[j+1][k]=temp
samp

array([[82, 22, 12],
       [34, 43, 73],
       [53, 94, 66]])

# Pandas

Question 6: Find the most expensive car company name
Print most expensive car’s company name and price.

Expected Output:

Python Pandas printing most costly car name

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('Automobile_data.csv')

In [44]:
df[['company','price']].max()

company    volvo
price      45400
dtype: object

Question 7: Find each company’s Higesht price car

In [20]:
df.groupby('company').max()

index body-style  wheel-base  length engine-type  \
company                                                           
alfa-romero        2  hatchback        94.5   171.2        ohcv   
audi               6      wagon       105.8   192.7         ohc   
bmw               15      sedan       110.0   197.0         ohc   
chevrolet         18      sedan        94.5   158.8         ohc   
dodge             20  hatchback        93.7   157.3         ohc   
honda             29      wagon        96.5   175.4         ohc   
isuzu             32      sedan        94.5   170.7         ohc   
jaguar            35      sedan       113.0   199.6        ohcv   
mazda             43      sedan       104.9   175.0       rotor   
mercedes-benz     47      wagon       120.9   208.1        ohcv   
mitsubishi        52      sedan        96.3   172.4         ohc   
nissan            57      wagon       100.4   184.6        ohcv   
porsche           63  hatchback        98.4   175.7        ohcf   
toyota            79      wagon       104.5   187.8         ohc   
volkswagen        86      sedan        97.3   171.7         ohc   
volvo             88      wagon       104.3   188.8         ohc   

              num-of-cylinders  horsepower  average-mileage    price  
company                                                               
alfa-romero                six         154               21  16500.0  
audi                      four         115               24  18920.0  
bmw                        six         182               23  41315.0  
chevrolet                three          70               47   6575.0  
dodge                     four          68               31   6377.0  
honda                     four         101               30  12945.0  
isuzu                     four          78               38   6785.0  
jaguar                  twelve         262               15  36000.0  
mazda                      two         101               31  18344.0  
mercedes-benz             five         184               22  45400.0  
mitsubishi                four          88               37   8189.0  
nissan                     six         152               45  13499.0  
porsche                    six         288               17  37028.0  
toyota                     six         156               35  15750.0  
volkswagen                four         100               37   9995.0  
volvo                     four         114               23  13415.0

Question 8: Concatenate two data frames using the following conditions
Create two data frames using the following two Dicts, Concatenate those two data frames and create a key for each data frame.

GermanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]}
japaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500 , 58900]}


In [31]:
GermanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]}
japaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500 , 58900]}

In [32]:
gc=pd.DataFrame(GermanCars)
jc=pd.DataFrame(japaneseCars)

In [33]:
gc

Company   Price
0      Ford   23845
1  Mercedes  171995
2       BMV  135925
3      Audi   71400

In [34]:
jc

Company  Price
0       Toyota  29995
1        Honda  23600
2       Nissan  61500
3  Mitsubishi   58900

In [38]:
pd.concat([gc,jc],keys=['G','J'])

Company   Price
G 0         Ford   23845
  1     Mercedes  171995
  2          BMV  135925
  3         Audi   71400
J 0       Toyota   29995
  1        Honda   23600
  2       Nissan   61500
  3  Mitsubishi    58900

Question 9: Sort all cars by Price column

In [40]:
df.sort_values('price')

index        company body-style  wheel-base  length engine-type  \
13     16      chevrolet  hatchback        88.4   141.1           l   
27     36          mazda  hatchback        93.1   159.1         ohc   
48     66         toyota  hatchback        95.7   158.7         ohc   
36     49     mitsubishi  hatchback        93.7   157.3         ohc   
28     37          mazda  hatchback        93.1   159.1         ohc   
..    ...            ...        ...         ...     ...         ...   
11     14            bmw      sedan       103.5   193.8         ohc   
35     47  mercedes-benz    hardtop       112.0   199.2        ohcv   
22     31          isuzu      sedan        94.5   155.9         ohc   
23     32          isuzu      sedan        94.5   155.9         ohc   
47     63        porsche  hatchback        98.4   175.7       dohcv   

   num-of-cylinders  horsepower  average-mileage    price  
13            three          48               47   5151.0  
27             four          68               30   5195.0  
48             four          62               35   5348.0  
36             four          68               37   5389.0  
28             four          68               31   6095.0  
..              ...         ...              ...      ...  
11              six         182               16  41315.0  
35            eight         184               14  45400.0  
22             four          70               38      NaN  
23             four          70               38      NaN  
47            eight         288               17      NaN  

[61 rows x 10 columns]

Question 10: Count total cars per company

In [43]:
df['company'].value_counts()

toyota           7
bmw              6
nissan           5
mazda            5
mercedes-benz    4
audi             4
volkswagen       4
mitsubishi       4
jaguar           3
chevrolet        3
honda            3
isuzu            3
alfa-romero      3
porsche          3
volvo            2
dodge            2
Name: company, dtype: int64